apiVersion: apps/v1
kind: Deployment
metadata:
  name: appli-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appli-web
  template:
    metadata:
      labels:
        app: appli-web
    spec:
      containers:
      - image: hrabia/appli-web
        name: appli-web
        env:
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DATABASE
          value: url_shortener_db
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: mysecretpassword
        ports:
        - containerPort: 80
